# -*- coding: utf-8 -*-
"""102317002_mashup_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlOq7nMDf0pct_HkR6E_CIanA6hg4Svf
"""

!nvidia-smi

# Install ffmpeg for pydub to handle audio, and the required Python libraries
!apt-get update
!apt-get install -y ffmpeg
!pip install yt-dlp pydub flask pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 102317002.py
# import sys
# import os
# from yt_dlp import YoutubeDL
# from pydub import AudioSegment
# 
# def create_mashup(singer, num_videos, duration, output_file):
#     print(f"Searching and downloading {num_videos} videos for '{singer}'...")
# 
#     ydl_opts = {
#         'format': 'bestaudio/best',
#         'extract_audio': True,
#         'audio_format': 'mp3',
#         'outtmpl': 'temp_audio_%(autonumber)s.%(ext)s',
#         'noplaylist': True,
#     }
# 
#     try:
#         with YoutubeDL(ydl_opts) as ydl:
#             ydl.download([f"ytsearch{num_videos}:{singer}"])
#     except Exception as e:
#         print(f"Error during download: {e}")
#         sys.exit(1)
# 
#     print("Processing and merging audio files...")
#     mashup = AudioSegment.empty()
# 
#     for file in sorted(os.listdir('.')):
#         if file.startswith('temp_audio_') and file.endswith('.mp3'):
#             try:
#                 audio = AudioSegment.from_file(file, format="mp3")
#                 sliced_audio = audio[:duration * 1000] # pydub works in milliseconds
#                 mashup += sliced_audio
#             except Exception as e:
#                 print(f"Could not process {file}: {e}")
#             finally:
#                 os.remove(file)
# 
#     try:
#         mashup.export(output_file, format="mp3")
#         print(f"Success! Mashup saved to {output_file}")
#     except Exception as e:
#         print(f"Error saving file: {e}")
# 
# def main():
#     if len(sys.argv) != 5:
#         print("Error: Incorrect number of parameters.")
#         print("Usage: python 102317002.py <SingerName> <NumberOfVideos> <AudioDuration> <OutputFileName>")
#         sys.exit(1)
# 
#     singer = sys.argv[1]
# 
#     try:
#         num_videos = int(sys.argv[2])
#         duration = int(sys.argv[3])
#         output_file = sys.argv[4]
#     except ValueError:
#         print("Error: <NumberOfVideos> and <AudioDuration> must be integers.")
#         sys.exit(1)
# 
#     create_mashup(singer, num_videos, duration, output_file)
# 
# if __name__ == "__main__":
#     main()
#

import os
os.makedirs('templates', exist_ok=True)

html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Mashup Web Service</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .container { max-width: 400px; padding: 20px; border: 1px solid #ccc; border-radius: 10px; }
        input[type="text"], input[type="number"], input[type="email"] { width: 90%; padding: 8px; margin-bottom: 15px; }
        input[type="submit"] { background-color: #28a745; color: white; padding: 10px 15px; border: none; cursor: pointer; }
    </style>
</head>
<body>
    <div class="container">
        <h2>Create an Audio Mashup</h2>
        <form action="/submit" method="POST">
            <label>Singer Name:</label><br>
            <input type="text" name="singer" value="Sharry Mann" required><br>

            <label># of videos ( > 10 ):</label><br>
            <input type="number" name="num_videos" min="11" value="11" required><br>

            <label>Duration of each video in sec ( > 20 ):</label><br>
            <input type="number" name="duration" min="21" value="21" required><br>

            <label>Email Id:</label><br>
            <input type="email" name="email" required><br>

            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>
"""
with open('templates/index.html', 'w') as f:
    f.write(html_content)
print("templates/index.html created successfully!")

from flask import Flask, render_template, request, send_file
import os
import zipfile
from yt_dlp import YoutubeDL
from pydub import AudioSegment

app = Flask(__name__)

# --- Auto-Create the HTML Template ---
# This ensures the templates folder and index.html exist when you run the app locally
os.makedirs('templates', exist_ok=True)
html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Mashup Web Service</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .container { max-width: 400px; padding: 20px; border: 1px solid #ccc; border-radius: 10px; }
        input[type="text"], input[type="number"] { width: 90%; padding: 8px; margin-bottom: 15px; }
        input[type="submit"] { background-color: #28a745; color: white; padding: 10px 15px; border: none; cursor: pointer; }
    </style>
</head>
<body>
    <div class="container">
        <h2>Create an Audio Mashup</h2>
        <form action="/submit" method="POST">
            <label>Singer Name:</label><br>
            <input type="text" name="singer" value="Sharry Mann" required><br>

            <label># of videos ( > 10 ):</label><br>
            <input type="number" name="num_videos" min="11" value="11" required><br>

            <label>Duration of each video in sec ( > 20 ):</label><br>
            <input type="number" name="duration" min="21" value="21" required><br>

            <input type="submit" value="Generate & Download">
        </form>
    </div>
</body>
</html>
"""
with open('templates/index.html', 'w') as f:
    f.write(html_content)
# -------------------------------------

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/submit', methods=['POST'])
def submit():
    singer = request.form['singer']
    num_videos = int(request.form['num_videos'])
    duration = int(request.form['duration'])

    output_mp3 = "mashup_local.mp3"
    output_zip = "102317002_mashup.zip"

    print(f"Starting download and processing for {singer}...")

    # 1. Download Audio
    ydl_opts = {
        'format': 'bestaudio/best',
        'extract_audio': True,
        'audio_format': 'mp3',
        'outtmpl': 'local_audio_%(autonumber)s.%(ext)s',
        'noplaylist': True
    }
    with YoutubeDL(ydl_opts) as ydl:
        ydl.download([f"ytsearch{num_videos}:{singer}"])

    # 2. Slice and Merge
    mashup = AudioSegment.empty()
    for file in sorted(os.listdir('.')):
        if file.startswith('local_audio_') and file.endswith('.mp3'):
            audio = AudioSegment.from_file(file, format="mp3")
            mashup += audio[:duration * 1000] # Convert to milliseconds
            os.remove(file) # Delete the individual file

    mashup.export(output_mp3, format="mp3")

    # 3. Create ZIP File
    with zipfile.ZipFile(output_zip, 'w') as zipf:
        zipf.write(output_mp3)

    # Clean up the standalone MP3 since it's now in the ZIP
    os.remove(output_mp3)

    print("Processing complete! Sending file to user...")

    # 4. Send the ZIP file back to the browser for download
    return send_file(output_zip, as_attachment=True)

if __name__ == '__main__':
    print("\n---> SERVER IS RUNNING LOCALLY AT: http://127.0.0.1:5000 <---\n")
    # Run the standard local Flask server
    app.run(debug=True, port=5000)